# Generated by Django 5.0.2 on 2024-02-15 18:22

import pgvector.django
import todo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=256)),
                ("due_date", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "embedding",
                    models.GeneratedField(
                        db_persist=True,
                        expression=todo.models.EmbedSmallExpression("description"),
                        output_field=pgvector.django.VectorField(dimensions=384),
                    ),
                ),
            ],
        ),
    ]
