# Generated by Django 5.0.2 on 2024-02-15 18:52

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="todoitem",
            index=pgvector.django.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="todoitem_embedding_hnsw_index",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
